<?php
define('KALALAYA', true);
require __DIR__ . '/includes/functions.php';
$page = [
    'id' => 'gallery',
    'title' => 'Kalalaya Fine Arts Gallery | Student & Master Artwork',
    'description' => 'Explore artworks by Kalalaya Fine Arts founder Mr. Anthony Raj and the talented students of our drawing and painting classes in Coimbatore.',
    'path' => 'gallery.php',
    'footer' => 'compact',
    'og_image' => 'assets/images/gallery/master-landscape.jpg',
    'scripts' => ['data/students.js', 'js/gallery.js'],
    'jsonld' => breadcrumb_jsonld([['Home', ''], ['Gallery', 'gallery.php']]),
];
require __DIR__ . '/includes/header.php';

/* Master's work — edit/add items here: [image, title, medium, year, alt] */
$masters = [
    ['master-landscape', 'Serene Landscape', 'Acrylic on Canvas', '2023', 'Acrylic landscape of a river winding through trees at sunset'],
    ['master-portrait', 'Graceful Portrait', 'Oil on Canvas', '2022', 'Oil portrait of a woman in traditional jewellery'],
    ['master-still-life', 'Still Life with Flowers', 'Oil on Canvas', '2021', 'Oil still life of flowers in a blue vase with fruit'],
    ['master-horse', 'Majestic Horse', 'Charcoal on Paper', '2020', 'Charcoal drawing of a horse’s head'],
];
?>

<section class="hero">
    <div class="container hero__grid">
        <div class="hero__copy">
            <span class="eyebrow">Kalalaya Fine Arts • Gallery</span>
            <h1 class="h-display">Our Art <span class="text-pink">Gallery</span></h1>
            <p class="muted">Explore a collection of inspiring artworks created by our master and talented students. Each piece reflects creativity, learning and the unique artistic journey at Kalalaya.</p>
        </div>
        <div class="hero__media brush-media">
            <img src="assets/images/gallery/hero-brushes.jpg" width="652" height="362" alt="Paint brushes in a glass jar in front of colourful canvases" fetchpriority="high">
        </div>
    </div>
    <nav class="container gallery-tabs" aria-label="Gallery sections" style="margin-top:32px">
        <a class="btn btn--primary btn--sm" href="#masters-work">Master’s Work</a>
        <a class="btn btn--outline btn--sm" href="#students-work" style="background:#fff">Students Work</a>
    </nav>
</section>

<section class="section" id="masters-work">
    <div class="container">
        <div class="section-head reveal">
            <span class="eyebrow">Master’s Work</span>
            <h2 class="h-section">Art by Our Master</h2>
            <p class="muted" style="margin-top:10px">A glimpse into the creative world of our founder, Mr Anthony Raj.</p>
        </div>
        <ul class="master-grid" data-lightbox-group="masters">
            <?php foreach ($masters as [$img, $title, $medium, $year, $alt]): ?>
            <li class="reveal">
                <figure class="art-card">
                    <button class="art-card__img" type="button" data-lightbox="assets/images/gallery/<?= $img ?>.jpg" data-caption="<?= e($title) ?>" data-sub="<?= e("$medium · $year") ?>" aria-label="View larger: <?= e($title) ?>"><img src="assets/images/gallery/<?= $img ?>.jpg" width="420" height="394" alt="<?= e($alt) ?>" loading="lazy"></button>
                    <figcaption><h3><?= e($title) ?></h3><p><?= e($medium) ?><span>|</span><?= e($year) ?></p></figcaption>
                </figure>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</section>

<div class="container"><hr class="divider"></div>

<section class="section" id="students-work">
    <div class="container">
        <div class="section-head reveal">
            <span class="eyebrow">Students Work</span>
            <h2 class="h-section">Our Talented Students</h2>
            <p class="muted" style="margin-top:10px;max-width:440px">Discover the creativity and hard work of our amazing students across various age groups and courses.</p>
        </div>

        <!-- Cards are generated by js/gallery.js from data/students.js -->
        <ul class="student-grid" id="student-grid" aria-live="polite"></ul>
        <noscript><p class="gallery-empty">Please enable JavaScript to browse the student gallery.</p></noscript>
        <nav class="pagination" id="student-pagination" aria-label="Student gallery pages"></nav>
    </div>
</section>

<?php require __DIR__ . '/includes/footer.php'; ?>
